### ISSUE TITLE
Question: why it's not based on  UltiSnips

### ISSUE THREAD

**Issue by butterflyfish** [ncm2/ncm2-snipmate#1]
ncm support UltiSnips, but ncm2-snipmate is not. Would you like to explain reason ? Would you upload a gif to demo what this plugin can do ?

**Comment by roxma** [comment]
Because I'm using snipmate currently.

Ultisnip binding will be created as another plugin, after I remove the experimental flag of this repo

**Comment by roxma** [comment]
>  Would you upload a gif to demo what this plugin can do ?

It would be the same as the gif of NCM README

Taking gif is time consuming. Just plain-text explanation for now.

**Comment by butterflyfish** [comment]
thank you very much!

**Comment by roxma** [comment]
Still kind of experimental. But I'm stuck integrating lsp stuff.  Let's get ultisnips integration first: https://github.com/ncm2/ncm2-ultisnips
